name: Deploy to Nekoweb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare build
        run: |
          mkdir -p ./build
          cp -r ./public/* ./build

      - name: Deploy to Nekoweb
        uses: mp-pinheiro/nekoweb-deploy@main
        with:

API_KEY: ${{ secrets.API_KEY }}
BUILD_DIR: ./website
DEPLOY_DIR: ./website
NEKOWEB_PAGENAME: 2205j00
ENCRYPTION_KEY: ${{ secrets.NEKOWEB_ENCRYPTION_KEY }}