

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      # your build step here
        
      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@v4
        with:
          nekoweb-api-key: fe1c692b8ecfeb6a84bfca7a16f4a2f884bea97fa6d93d795dab782b2abb7c02 
          nekoweb-cookie: ${{ secrets.NEKOWEB_COOKIE }}
          nekoweb-folder: 'website'
          directory: 'website'


